<?php
$things = [
  // resources
  "compound" => [
    "id" => 0,
    "actions" => ["collect_a_stack"],
    "url" => "/8/83/CompoundResource.png",
    "category" => "resources",
    "selected_by_default" => false,
  ],
  "resin" => [
    "id" => 1,
    "actions" => ["collect_a_stack"],
    "url" => "/c/c3/ResinResource.png",
    "category" => "resources",
    "selected_by_default" => false,
  ],
  "laterite" => [
    "id" => 2,
    "actions" => ["collect_a_stack", "smelt"],
    "url" => "/9/90/Laterite_stack.jpg",
    "category" => "resources",
    "selected_by_default" => true,
  ],
  "malachite" => [
    "id" => 3,
    "actions" => ["collect_a_stack", "smelt"],
    "url" => "/7/7e/Malachite_stack.jpg",
    "category" => "resources",
    "selected_by_default" => true,
  ],
  "aluminum" => [
    "id" => 4,
    "actions" => ["collect_a_stack"],
    "url" => "/2/20/AluminumStack.png",
    "category" => "resources",
    "selected_by_default" => true,
  ],
  "copper" => [
    "id" => 5,
    "actions" => ["collect_a_stack"],
    "url" => "/2/2b/Copper_stack.jpg",
    "category" => "resources",
    "selected_by_default" => true,
  ],
  "titanium" => [
    "id" => 6,
    "actions" => ["collect_a_stack"],
    "url" => "/6/6c/Titanium_stack.jpg",
    "category" => "resources",
    "selected_by_default" => true,
  ],
  "lithium" => [
    "id" => 7,
    "actions" => ["collect_a_stack"],
    "url" => "/4/4b/Lithium_stack.jpg",
    "category" => "resources",
    "selected_by_default" => true,
  ],
  "coal" => [
    "id" => 8,
    "actions" => ["collect_a_stack"],
    "url" => "/a/a7/Coal.png",
    "category" => "resources",
    "selected_by_default" => true,
  ],
  "organic" => [
    "id" => 9,
    "actions" => ["collect_a_stack"],
    "url" => "/d/d8/Small_generator_organic.jpg",
    "category" => "resources",
    "selected_by_default" => false,
  ],
  "hydrazine" => [
    "id" => 10,
    "actions" => ["collect_a_stack"],
    "url" => "/b/bc/Hydrazine.png",
    "category" => "resources",
    "selected_by_default" => true,
  ],
  "hematite" => [
    "id" => 11,
    "actions" => ["collect_a_stack"],
    "url" => "/a/a5/HematiteResource.png",
    "category" => "resources",
    "selected_by_default" => false,
  ],
  "astronium" => [
    "id" => 12,
    "actions" => ["collect_a_stack"],
    "url" => "/5/5a/AstroniumResource.png",
    "category" => "resources",
    "selected_by_default" => false,
  ],
  "oxygen" => [
    "id" => 13,
    "actions" => ["collect_a_stack"],
    "url" => "/0/0b/Oxygen_stacks.jpg",
    "category" => "resources",
    "selected_by_default" => false,
  ],
  "power" => [
    "id" => 14,
    "actions" => ["collect_a_stack"],
    "url" => "/b/b3/PowerResource.png",
    "category" => "resources",
    "selected_by_default" => false,
  ],

  // planets
  "terran" => [
    "id" => 15,
    "actions" => ["go_to_planet"],
    "url" => "/b/b0/Terran.png",
    "category" => "planets",
    "selected_by_default" => false,
  ],
  "barren" => [
    "id" => 16,
    "actions" => ["go_to_planet"],
    "url" => "/7/78/Barren.png",
    "category" => "planets",
    "selected_by_default" => false,
  ],
  "exotic" => [
    "id" => 17,
    "actions" => ["go_to_planet"],
    "url" => "/d/de/Exoitc.png",
    "category" => "planets",
    "selected_by_default" => false,
  ],
  "radiated" => [
    "id" => 18,
    "actions" => ["go_to_planet"],
    "url" => "/9/99/Radiated.png",
    "category" => "planets",
    "selected_by_default" => false,
  ],
  "arid" => [
    "id" => 19,
    "actions" => ["go_to_planet"],
    "url" => "/6/6a/Arid.png",
    "category" => "planets",
    "selected_by_default" => false,
  ],
  "tundra" => [
    "id" => 20,
    "actions" => ["go_to_planet"],
    "url" => "/1/17/Tundra.png",
    "category" => "planets",
    "selected_by_default" => false,
  ],

  // modules
  "platform" => [
    "id" => 21,
    "actions" => ["print"],
    "url" => "",
    "category" => "buildings",
    "selected_by_default" => false,
  ],
  "module_platform" => [
    "id" => 22,
    "actions" => ["print"],
    "url" => "/c/c1/Module-platform-example.jpg",
    "category" => "buildings",
    "selected_by_default" => false,
  ],
  "printer" => [
    "id" => 23,
    "actions" => ["print"],
    "url" => "/9/98/Printer.png",
    "category" => "buildings",
    "selected_by_default" => true,
  ],
  "smelter" => [
    "id" => 24,
    "actions" => ["print"],
    "url" => "/4/45/Smelter.png",
    "category" => "buildings",
    "selected_by_default" => true,
  ],
  "vehicle_bay" => [
    "id" => 25,
    "actions" => ["print"],
    "url" => "/c/c3/VehicleBay2.png",
    "category" => "buildings",
    "selected_by_default" => true,
  ],
  "research" => [
    "id" => 26,
    "actions" => ["print"],
    "url" => "/b/b9/Research_Station.jpg",
    "category" => "buildings",
    "selected_by_default" => true,
  ],
  "fuel_condenser" => [
    "id" => 27,
    "actions" => ["print", "research_blueprint"],
    "url" => "/3/39/FuelCondenser.png",
    "category" => "buildings",
    "selected_by_default" => true,
  ],
  "trade_platform" => [
    "id" => 28,
    "actions" => ["print", "research_blueprint"],
    "url" => "/f/f0/TradePlatform.png",
    "category" => "buildings",
    "selected_by_default" => true,
  ],

  // backpack items
  "small_solar_panel" => [
    "id" => 29,
    "actions" => ["print"],
    "url" => "/2/25/Solar.png",
    "category" => "backpack_items",
    "selected_by_default" => false,
  ],
  "small_battery" => [
    "id" => 30,
    "actions" => ["print"],
    "url" => "",
    "category" => "backpack_items",
    "selected_by_default" => true,
  ],
  "small_generator" => [
    "id" => 31,
    "actions" => ["print"],
    "url" => "",
    "category" => "backpack_items",
    "selected_by_default" => true,
  ],
  "beacon" => [
    "id" => 32,
    "actions" => ["print"],
    "url" => "",
    "category" => "backpack_items",
    "selected_by_default" => false,
  ],
  "tank" => [
    "id" => 33,
    "actions" => ["print"],
    "url" => "",
    "category" => "backpack_items",
    "selected_by_default" => true,
  ],
  "wind_vane" => [
    "id" => 34,
    "actions" => ["print"],
    "url" => "/f/fc/Wind_Vane.png",
    "category" => "backpack_items",
    "selected_by_default" => true,
  ],
  "tether" => [
    "id" => 35,
    "actions" => ["print"],
    "url" => "",
    "category" => "backpack_items",
    "selected_by_default" => false,
  ],
  "filters" => [
    "id" => 36,
    "actions" => ["print", "research_blueprint"],
    "url" => "",
    "category" => "backpack_items",
    "selected_by_default" => true,
  ],
  "power_cells" => [
    "id" => 37,
    "actions" => ["print", "research_blueprint"],
    "url" => "",
    "category" => "backpack_items",
    "selected_by_default" => true,
  ],

  // printer item
  "solar_panel" => [
    "id" => 38,
    "actions" => ["print"],
    "url" => "/d/df/SolarPanel.png",
    "category" => "printer_items",
    "selected_by_default" => false,
  ],
  "battery" => [
    "id" => 39,
    "actions" => ["print"],
    "url" => "/6/6d/Battery.png",
    "category" => "printer_items",
    "selected_by_default" => true,
  ],
  "wind_turbine" => [
    "id" => 40,
    "actions" => ["print"],
    "url" => "/3/3e/Wind_Turbine.png",
    "category" => "printer_items",
    "selected_by_default" => true,
  ],
  "storage" => [
    "id" => 41,
    "actions" => ["print"],
    "url" => "/4/48/Storage.png",
    "category" => "printer_items",
    "selected_by_default" => false,
  ],
  "1_seat" => [
    "id" => 42,
    "actions" => ["print"],
    "url" => "/6/69/1-seat.png",
    "category" => "printer_items",
    "selected_by_default" => false,
  ],
  "generator" => [
    "id" => 43,
    "actions" => ["print", "research_blueprint"],
    "url" => "/c/c2/Generator.png",
    "category" => "printer_items",
    "selected_by_default" => true,
  ],
  "habitat" => [
    "id" => 44,
    "actions" => ["print", "research_blueprint"],
    "url" => "/4/49/Habitat.jpg",
    "category" => "printer_items",
    "selected_by_default" => true,
  ],
  "winch" => [
    "id" => 45,
    "actions" => ["print", "research_blueprint"],
    "url" => "/3/31/Winch.png",
    "category" => "printer_items",
    "selected_by_default" => true,
  ],
  "drill_head" => [
    "id" => 46,
    "actions" => ["print", "research_blueprint"],
    "url" => "",
    "category" => "printer_items",
    "selected_by_default" => true,
  ],

  // vehicle items
  "vehicle_1_seat" => [
    "id" => 47,
    "actions" => ["print"],
    "url" => "",
    "category" => "vehicle_items",
    "selected_by_default" => false,
  ],
  "vehicle_storage" => [
    "id" => 48,
    "actions" => ["print", "research_blueprint"],
    "url" => "",
    "category" => "vehicle_items",
    "selected_by_default" => true,
  ],
  "3_seat" => [
    "id" => 49,
    "actions" => ["print", "research_blueprint"],
    "url" => "",
    "category" => "vehicle_items",
    "selected_by_default" => true,
  ],
  "crane" => [
    "id" => 50,
    "actions" => ["print", "research_blueprint"],
    "url" => "",
    "category" => "vehicle_items",
    "selected_by_default" => true,
  ],

  // vehicles
  "rover" => [
    "id" => 51,
    "actions" => ["print"],
    "url" => "/9/96/Rover.jpg",
    "category" => "vehicles",
    "selected_by_default" => false,
  ],
  "shuttle" => [
    "id" => 52,
    "actions" => ["print"],
    "url" => "",
    "category" => "vehicles",
    "selected_by_default" => false,
  ],
  "spaceship" => [
    "id" => 53,
    "actions" => ["print", "research_blueprint"],
    "url" => "/2/21/Spaceship.png",
    "category" => "vehicles",
    "selected_by_default" => true,
  ],
  "truck" => [
    "id" => 54,
    "actions" => ["print", "research_blueprint"],
    "url" => "/3/37/AstroneerTruck.jpg",
    "category" => "vehicles",
    "selected_by_default" => true,
  ],

  // spire fountains
  "oxygen_spire" => [
    "id" => 55,
    "actions" => ["collect_from_fountain"],
    "url" => "/3/3d/Oxygen_Spire.jpg",
    "category" => "resource_fountains",
    "selected_by_default" => false,
  ],
  "power_spire" => [
    "id" => 56,
    "actions" => ["collect_from_fountain"],
    "url" => "/d/d4/Resource-Spire-power.jpg",
    "category" => "resource_fountains",
    "selected_by_default" => false,
  ],
  "compound_spire" => [
    "id" => 57,
    "actions" => ["collect_from_fountain"],
    "url" => "/c/cb/Compound_Spire.jpg",
    "category" => "resource_fountains",
    "selected_by_default" => true,
  ],
  "resin_spire" => [
    "id" => 58,
    "actions" => ["collect_from_fountain"],
    "url" => "/7/7d/Resin_Spire.jpg",
    "category" => "resource_fountains",
    "selected_by_default" => true,
  ],

  // research items
  "research_chest_sphere_red_hair" => [
    "id" => 59,
    "actions" => ["research_chest"],
    "url" => "/e/e7/Research_red_ball_hair.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_sphere_red_green" => [
    "id" => 60,
    "actions" => ["research_chest"],
    "url" => "/7/7f/Research_green_ball_hair.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_barbecue_white_rounded_top" => [
    "id" => 61,
    "actions" => ["research_chest"],
    "url" => "/c/c7/Space-research.PNG",
    "category" => "research_chests",
    "selected_by_default" => true,
  ],
  "research_chest_barbecue_white_flat_top" => [
    "id" => 62,
    "actions" => ["research_chest"],
    "url" => "/2/28/Research_flat_barbecue.jpg",
    "category" => "research_chests",
    "selected_by_default" => true,
  ],
  "research_chest_barbecue_cylinder_blue" => [
    "id" => 63,
    "actions" => ["research_chest"],
    "url" => "/c/c5/Research_Canister.jpg",
    "category" => "research_chests",
    "selected_by_default" => true,
  ],
  "research_chest_barbecue_cube_lego" => [
    "id" => 64,
    "actions" => ["research_chest"],
    "url" => "/b/bb/Research_white_lego.jpg",
    "category" => "research_chests",
    "selected_by_default" => true,
  ],
  "research_chest_cube_yellow" => [
    "id" => 65,
    "actions" => ["research_chest"],
    "url" => "/4/4f/Research_yellow_cubiod.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_cube_orange" => [
    "id" => 66,
    "actions" => ["research_chest"],
    "url" => "/2/2f/Research_orange_cubiod.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_cube_white" => [
    "id" => 67,
    "actions" => ["research_chest"],
    "url" => "/a/aa/Research_gray_cube.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_cube_green_orange_cristals" => [
    "id" => 68,
    "actions" => ["research_chest"],
    "url" => "0/03/Research_green_orange_crystal.jpg",
    "category" => "research_chests",
    "selected_by_default" => true,
  ],
  "research_chest_cube_cyan_red_green_cristals" => [
    "id" => 69,
    "actions" => ["research_chest"],
    "url" => "/3/39/Research_cyan_red_crystal.jpg",
    "category" => "research_chests",
    "selected_by_default" => true,
  ],
  "research_chest_blob_pink" => [
    "id" => 70,
    "actions" => ["research_chest"],
    "url" => "/e/e9/Research_pink_blob.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_blob_cyan" => [
    "id" => 71,
    "actions" => ["research_chest"],
    "url" => "/8/80/Research_blue-green_blob.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_sphere_green_blue_cristals" => [
    "id" => 72,
    "actions" => ["research_chest"],
    "url" => "/e/e0/Research_round_blue_crystal.jpg",
    "category" => "research_chests",
    "selected_by_default" => true,
  ],
  "research_chest_sphere_purple_red_cristals" => [
    "id" => 73,
    "actions" => ["research_chest"],
    "url" => "f/f4/Research_dark_purple_round_red_crystal.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_sphere_green_bumped" => [
    "id" => 74,
    "actions" => ["research_chest"],
    "url" => "/4/4d/Research_green_bumped_sphere.jpg",
    "category" => "research_chests",
    "selected_by_default" => true,
  ],
  "research_chest_sphere_grey_bumped_blue_strip" => [
    "id" => 75,
    "actions" => ["research_chest"],
    "url" => "/1/1e/Research_grey_bumped_sphere.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_cuboid_red_green_part" => [
    "id" => 76,
    "actions" => ["research_chest"],
    "url" => "/4/4c/Research_Pod.png",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],
  "research_chest_cuboid_blue_orange_part" => [
    "id" => 77,
    "actions" => ["research_chest"],
    "url" => "/b/be/Research_blue_red_bits.jpg",
    "category" => "research_chests",
    "selected_by_default" => false,
  ],

  // hazards
  "exploder" => [
    "id" => 78,
    "actions" => ["kill", "get_killed"],
    "url" => "/1/1a/Hazard-Exploders.jpg",
    "category" => "hazards",
    "selected_by_default" => false,
  ],
  "gaz_pumkin" => [
    "id" => 79,
    "actions" => ["kill", "get_killed"],
    "url" => "/e/e4/Hazard-Spewers.jpg",
    "category" => "hazards",
    "selected_by_default" => false,
  ],
  "spiker" => [
    "id" => 80,
    "actions" => ["kill", "get_killed"],
    "url" => "",
    "category" => "hazards",
    "selected_by_default" => true,
  ],
  "lure_plant" => [
    "id" => 81,
    "actions" => ["kill", "get_killed"],
    "url" => "/a/a5/Lure.jpg",
    "category" => "hazards",
    "selected_by_default" => true,
  ],
  "worm" => [
    "id" => 82,
    "actions" => ["get_killed"],
    "url" => "/6/60/Hazard-Worm.jpg",
    "category" => "hazards",
    "selected_by_default" => false,
  ],
  "tumbleweeds" => [
    "id" => 83,
    "actions" => ["get_killed"],
    "url" => "/a/ae/Hazard-Tumbleweeds.jpg",
    "category" => "hazards",
    "selected_by_default" => false,
  ],
  "storm" => [
    "id" => 84,
    "actions" => ["get_killed"],
    "url" => "/3/3f/Astroneer-storm-alpha.jpg",
    "category" => "hazards",
    "selected_by_default" => false,
  ],

  // discoveries
  "crashed_ship" => [
    "id" => 85,
    "actions" => ["find"],
    "url" => "/c/ca/LargeWhiteCylinder.png",
    "category" => "discoveries",
    "selected_by_default" => true,
  ],
  "crashed_pod" => [
    "id" => 86,
    "actions" => ["find"],
    "url" => "/3/34/CrashedPod.PNG",
    "category" => "discoveries",
    "selected_by_default" => true,
  ],
  "solar_array" => [
    "id" => 87,
    "actions" => ["find"],
    "url" => "/b/be/CrashedSolar.png",
    "category" => "discoveries",
    "selected_by_default" => true,
  ],
  "resource_drop" => [
    "id" => 88,
    "actions" => ["find"],
    "url" => "/f/fe/ResourceDropOpen.png",
    "category" => "discoveries",
    "selected_by_default" => true,
  ],
  "spoutnik" => [
    "id" => 89,
    "actions" => ["find"],
    "url" => "/7/7a/Sputnik.png",
    "category" => "discoveries",
    "selected_by_default" => false,
  ],
  "mariner_10" => [
    "id" => 90,
    "actions" => ["find"],
    "url" => "/4/44/Mariner_10_%282%29.jpg",
    "category" => "discoveries",
    "selected_by_default" => false,
  ],
  "voyager" => [
    "id" => 91,
    "actions" => ["find"],
    "url" => "/d/d2/Voyager.jpg",
    "category" => "discoveries",
    "selected_by_default" => false,
  ],
  "hubble" => [
    "id" => 92,
    "actions" => ["find"],
    "url" => "/5/5c/Satelite.jpg",
    "category" => "discoveries",
    "selected_by_default" => false,
  ],
  "new_horizons" => [
    "id" => 93,
    "actions" => ["find"],
    "url" => "/6/6c/New_Horizons.png",
    "category" => "discoveries",
    "selected_by_default" => false,
  ],
  "kepler" => [
    "id" => 94,
    "actions" => ["find"],
    "url" => "/2/24/Kepler.jpg",
    "category" => "discoveries",
    "selected_by_default" => false,
  ],
  "dead_body" => [
    "id" => 95,
    "actions" => ["find"],
    "url" => "/5/51/DeadExplorer.png",
    "category" => "discoveries",
    "selected_by_default" => true,
  ],
  "rib_cage" => [
    "id" => 96,
    "actions" => ["find"],
    "url" => "",
    "category" => "discoveries",
    "selected_by_default" => false,
  ],
  "thruster" => [
    "id" => 97,
    "actions" => ["find"],
    "url" => "/6/62/Thruster.png",
    "category" => "discoveries",
    "selected_by_default" => false,
  ],
  "dynamite" => [
    "id" => 98,
    "actions" => ["find"],
    "url" => "/f/fc/Dynamite.png",
    "category" => "discoveries",
    "selected_by_default" => true,
  ],

  // allmighty gods
  "zebra_ball" => [
    "id" => 99,
    "actions" => ["find"],
    "url" => "/3/3c/Zebra_Ball.jpg",
    "category" => "allmighty_gods",
    "selected_by_default" => false,
  ],
  "chess_ball" => [
    "id" => 100,
    "actions" => ["find"],
    "url" => "/b/bf/Disco_Ball.jpg",
    "category" => "allmighty_gods",
    "selected_by_default" => false,
  ],
  "dalmatian_ball" => [
    "id" => 101,
    "actions" => ["find"],
    "url" => "/5/5d/Polka_Ball.jpg",
    "category" => "allmighty_gods",
    "selected_by_default" => false,
  ],
];

$actions = [
  "collect_a_stack",
  "collect_from_fountain",
  "smelt",
  "go_to_planet",
  "print",
  "research_chest",
  "research_blueprint",
  "get_killed",
  "kill",
  "find",
];

$wikiCDNUrl = "https://hydra-media.cursecdn.com/astroneer.gamepedia.com";


/*$data = [
  [ "strId" => "compound" ],
  [ "strId" => "resin" ],
];*/

